### ISSUE TITLE
libssh2.dll does not load on Windows 10

### ISSUE THREAD

**Issue by STemirov** [pult/libssh2_delphi#11]
libssh2.dll does not load on Windows 10

**Comment by pult** [comment]
In a good question, there is a 50% answer. You have 0%.

**Comment by marquardtnico** [comment]
> 
> 
> libssh2.dll does not load on Windows 10

I've got the same problem here. On my local machine it works fine, but if I try to start the .exe on a different machine (i tried it on win10 and winserver2019) i get the Error "Exception ELoadLibrary in module sftpTest.exe at 0020C935. Could not load library libssh2.dll". 

I copied the dll (wich works) into the direction where i try to start the .exe but that didn't helped unfortunetly.

**Comment by pult** [comment]
Typically, this situation occurs when x64 is used instead of x86, or vice versa. Here I can not help, because Everything depends on you. Use the debugger to understand the reason ...

libeay32.dll
libssh2.dll
ssleay32.dll

These DLLs may work differently on different Windows. Recent versions require VS Runtime.
A variant of these DLLs from the archive works for me on Windows 10 x64, Windows Server 2012.

**Comment by marquardtnico** [comment]
Thank you for your answer, it helped me to solve the problem. I recognized that the dll's were loaded from my installation from nmap. They're working as well on my other Windows 10 workstation, but not on the Windows Server 2019. Because i couldnt find the proper dll's for it i've installed nmap also on the server and now it is working.

**Comment by marquardtnico** [comment]
> 
> 
> Thank you for your answer, it helped me to solve the problem. I recognized that the dll's were loaded from my installation from nmap. They're working as well on my other Windows 10 workstation, but not on the Windows Server 2019. Because i couldnt find the proper dll's for it i've installed nmap also on the server and now it is working.

I found out what why it didn't worked out before that. In my case, the Microsoft Visual C++ 2013 Redistributable (x86) was needed to be installed.

**Comment by ezurschmiede** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.

Ich bin bis am 4.1.2020 in den Festtagsferien. Die eingehenden E-Mails werden während dieser Zeit nicht bearbeitet.

Schöne Festtage und en guete, gsunde Rutsch - bis im 2021,

Schöne Grüsse
Elias Zurschmiede

delight software gmbh
